import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./context/Provider";
import Header from "@/components/layout/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Provider>
        <body className={poppins.className}>
          <main className='max-w-7xl mx-auto p-2'>
            <Header />
            {children}
          </main>
        </body>
      </Provider>
    </html>
  );
}
